export const mockData = [
    {
        title: "Flat Rob",
        details: ["0 captures", "undeployed 1046 days ago"],
    },
    {
        title: "Virtual",
        details: ["0 captures"],
    },
    {
        title: "Void Mystery",
        details: ["0 captures"],
    },
    {
        title: "Tech Issues Card",
        details: ["0 captures"],
    },
    {
        title: "Summer Card",
        details: ["0 captures"],
    },
];

export const searchData = [
    { type: '0', pin: 'munzee.png' },
    { type: '1', pin: 'mystery.png' },
    { type: '532', pin: 'firemystery.png' },
    { type: '651', pin: 'icemystery.png' },
    { type: '851', pin: 'earthmystery.png' },
    { type: '1020', pin: 'watermystery.png' },
    { type: '1086', pin: 'airmystery.png' },
    { type: '2391', pin: 'electricmystery.png' },
    { type: '3295', pin: 'voidmystery.png' },
    { type: '13', pin: 'premium.png' },
    { type: '40', pin: 'diamond.png' },
    { type: '131', pin: 'ruby.png' },
    { type: '218', pin: 'aquamarine.png' },
    { type: '242', pin: 'topaz.png' },
    { type: '584', pin: 'pinkdiamond.png' },
    { type: '681', pin: 'virtual_sapphire.png' },
    { type: '2361', pin: 'virtual_citrine.png' },
    { type: '2362', pin: 'virtual_onyx.png' },
    { type: '290', pin: 'virtual_amethyst.png' },
    { type: '148', pin: 'virtualemerald.png' },
    { type: '70', pin: 'motel.png' },
    { type: '170', pin: 'hotel.png' },
    { type: '470', pin: '3starresort.png' },
    { type: '2183', pin: 'vacationcondo.png' },
    { type: '970', pin: 'timesharemunzee.png' },
    { type: '2145', pin: 'treehouse.png' },
    { type: '2426', pin: 'skyland.png' },
    { type: '3580', pin: 'tpobpub.png' },
    { type: '3724', pin: 'scrapstar.png' },
    { type: '3862', pin: 'teapob.png' },
    { type: '3961', pin: 'eventhostlounge.png', displayAfter:'2022-09-01T00:00:00-05:00' },
    { type: '510511', pin: 'reseller.png' },
    { type: '28862887', pin: 'virtualreseller.png' },
    { type: '500', pin: 'scatter.png' },
    { type: '444', pin: 'prizewheel.png' },
    { type: '522', pin: 'rockpaperscissors.png' },
    { type: '1643', pin: 'bowlingball.png' },
    { type: '19762002', pin: 'joystickfull.png' },
    { type: '1824', pin: 'urbanfit.png' },
    { type: '3274', pin: 'walnutchessset.png' },
    { type: '400', pin: 'surprise.png' },
    { type: '2412', pin: 'sirprizewheel.png' },
    { type: '3281', pin: 'maplechessset.png' },
    { type: '1139', pin: 'winterseasonalmunzee.png' },
    { type: '308312', pin: 'zodiac-sun.png' },
    { type: '12711272', pin: 'chinesezodiacsun.png' },
    { type: '27512752', pin: 'egyptianzodiacsun.png' },
    { type: '40354036', pin: 'celticzodiacfilter.png', displayAfter:'2022-11-01T00:00:01-05:00' },
    { type: '3', pin: 'virtual_rainbow.png' },
    { type: '1245', pin: 'temporaryvirtual.png' },
    { type: '353', pin: 'flatrob.png' },
    { type: '1015', pin: 'flatmatt.png' },
    { type: '1338', pin: 'flatlou.png' },
    { type: '1581', pin: 'flathammock.png' },
    { type: '2903', pin: 'flatdhs.png' },
    { type: '2904', pin: 'flatdiscgolfbasket.png' },
    { type: '2905', pin: 'flatflashlight.png' },
    { type: '2906', pin: 'flattypewriter.png' },
    { type: '2907', pin: 'flatmurray.png' },
    { type: '2908', pin: 'flatrum.png' },
    { type: '2909', pin: 'flatcats.png' },
    { type: '2910', pin: 'flatvan.png', displayAfter:'2022-07-09T00:00:00-05:00' },
    { type: '52', pin: 'mace.png' },
    { type: '53', pin: 'longsword.png' },
    { type: '140', pin: 'battleaxe.png' },
    { type: '306', pin: 'thehammer.png' },
    { type: '998', pin: 'crossbow.png' },
    { type: '1248', pin: 'catapult.png' },
    { type: '3244', pin: 'shield.png' },
    { type: '1246', pin: 'briefcase.png' },
    { type: '2824', pin: 'walkietalkiewatch.png' },
    { type: '3417', pin: 'physicalmasterofdisguise.png' },
    { type: '1359', pin: 'nightvisiongoggles.png' },
    { type: '3418', pin: 'virtualmasterofdisguise.png' },
    { type: '190', pin: 'trail.png' },
    { type: '390', pin: 'virtual_trail.png' },
    { type: '200', pin: 'personalmunzee.png' },
    { type: '441', pin: 'shamrock.png' },
    { type: '2941', pin: 'virtualshamrock.png' },
    { type: '91', pin: 'poi_filter.png' },
    { type: '24202421', pin: 'envelope.png' },
    { type: '735736', pin: 'evolution.png' },
    { type: '1760', pin: 'rose.png' },
    { type: '1761', pin: 'tulip.png' },
    { type: '1774', pin: 'lily.png' },
    { type: '1797', pin: 'carnation.png' },
    { type: '1830', pin: 'morphobutterfly_physical.png' },
    { type: '2067', pin: 'treefrog_physical.png' },
    { type: '2452', pin: 'seaturtle_physical.png' },
    { type: '2461', pin: 'boxjellyfish_physical.png' },
    { type: '2876', pin: 'honeybee_physical.png' },
    { type: '3685', pin: 'mallard_physical.png', displayAfter:'2022-04-05T12:00:00-05:00' },
]